#!/usr/bin/env python

import os
from typing_extensions import Literal


class TUI:
    def __init__(self) -> None:
        pass

    def clear(self) -> None:
        os.system('clear')

    def message(self, msg) -> Literal[False] | None:
        if msg == "":
            return False
        print(f">> {msg}")

    def error(self, msg) -> Literal[False] | None:
        if msg == "":
            return False
        print(f"!! {msg}")

    def warning(self, msg) -> Literal[False] | None:
        if msg == "":
            return False
        print(f"$$ {msg}")


class Writer:
    def __init__(self) -> None:
        pass

    def run(self) -> None:
        pass


if __name__ == "__main__":
    writer = Writer()
    writer.run()
