#!/usr/bin/env python


import os
import sys
from PIL import ImageGrab

def get_screensize():
    img = ImageGrab.grab()
    return img.size[0], img.size[1]


def check_extension(filename):
    has_extension = False
    extension = ".mp4"
    if "." in filename:
        has_extension = True
    else:
        extension = ".mp4"

    if has_extension:
        extension = os.path.splitext(filename)[1]
    return extension.lower()


def start_capture(args):

    filename = sys.argv[1]
    if check_extension(filename) not in filename:
        filename += check_extension(filename)
    width, height = get_screensize()
    cmd = "ffmpeg -y "
    cmd += f"-video_size {width}x{height} "
    cmd += "-thread_queue_size 4096 "
    cmd += "-framerate 25 -f x11grab "
    cmd += "-draw_mouse 0 "
    cmd += "-i :0.0 -f pulse "
    cmd += "-ac 2 -i default "
    cmd += f"{filename}"
    os.system('clear')
    print(f"Recording to: {filename}")
    print("Press [ENTER] to start recording")
    os.system(cmd)


if __name__ == "__main__":
    if len(sys.argv) == 1:
        print('Please provide a filename.')
        print('If you don\'t add the extension, I will add .mp4.')
        exit()
    else:
        start_capture(sys.argv)
