#!/usr/bin/env python
from utils import Utils


class StoryTeller(Utils):
    def __init__(self):
        super().__init__()

    def change_title(self):
        insubmenu = True
        while insubmenu:
            self.render_title(title='Change Title')
            validkeys = self.render_change_title_menu()

            cmd = self.user_input()
            if cmd not in validkeys:
                self.print_error('That is not a valid option...', wait=True)
            elif cmd == 'r':
                insubmenu = False
            else:
                self.do_change_title(int(cmd))

    def run(self):
        self.check_if_storydir_exists()
        self.load_config()
        running = True
        while running:
            self.render_title()
            validkeys = self.render_menu()

            cmd = self.user_input()
            if cmd not in validkeys:
                self.print_error('That is not a valid option...', wait=True)
            elif cmd == 'q':
                running = False
            elif cmd == 'c':
                self.continue_story()
            elif cmd == 'n':
                self.tell_a_new_story()
            elif cmd == 't':
                self.change_title()
            elif cmd == 'd':
                self.delete_story()
            else:
                self.open_story(int(cmd))


if __name__ == "__main__":
    app = StoryTeller()
    app.run()
