#!/usr/bin/env python
# ----------------------------------------------------------------------
# Behang is Dutch for wallpaper, thought it was funny to call it this,
# but decided against it and just call the main executable 'wp'
# ----------------------------------------------------------------------

import os
import sys
import random

from subprocess import getoutput, Popen, PIPE
from pathlib import Path
from time import sleep

#!/usr/bin/env python

import os
import sys
import glob
import toml

from pathlib import Path
from shutil import get_terminal_size
from time import sleep

# ----------------------------------------------------
# ----- CLASS Colors
# ----------------------------------------------------

class Colors:
    reset = "\033[0m"
    black = "\033[30m"
    red = "\033[31m"
    green = "\033[32m"
    yellow = "\033[33m"
    blue = "\033[34m"
    pink = "\033[35m"
    cyan = "\033[36m"
    white = "\033[37m"

# ----------------------------------------------------
# ----- CLASS Tools
# ----------------------------------------------------

class Tools:
    def __init__(self):
        self.colors = Colors()
        self.cols = get_terminal_size().columns

    # ----------------------------------------------------
    # ----- HELPER FUNCTIONS
    # ----------------------------------------------------
    def replace_color_codes(self, line):
        """Replace codes in a line with the corresponding color"""
        codes = [
            '{res}', '{black}', '{red}', '{green}',
            '{yellow}', '{blue}', '{pink}', '{cyan}',
            '{white}'
        ]
        colors = [
            self.colors.reset, self.colors.black, self.colors.red,
            self.colors.green, self.colors.yellow, self.colors.blue,
            self.colors.pink, self.colors.cyan, self.colors.white
        ]
        for c, code in enumerate(codes):
            line = line.replace(code, colors[c])
        return line

    def remove_color_codes(self, line):
        """Remove the codes from a line"""
        codes = [
            '{res}', '{black}', '{red}', '{green}',
            '{yellow}', '{blue}', '{ping}', '{cyan}',
            '{white}'
        ]
        for code in codes:
            line = line.replace(code, '')
        return line

    def remove_colors(self, line):
        """Remove the colors from a line"""
        colors = [
            self.colors.reset, self.colors.black, self.colors.red,
            self.colors.green, self.colors.yellow, self.colors.blue,
            self.colors.pink, self.colors.cyan, self.colors.white
        ]
        for color in colors:
            line = line.replace(color, '')
        return line

    # ----------------------------------------------------
    # ----- TERMINAL USER INTERFACE
    # ----------------------------------------------------
    def clear(self):
        """Clear the terminal"""
        os.system('clear')

    def hide_cursor(self):
        """Hide the cursor"""
        sys.stdout.write("\033[?25l")
        sys.stdout.flush()

    def show_cursor(self):
        """Show the cursor"""
        sys.stdout.write("\033[?25h")
        sys.stdout.flush()

    def cprint(self, message):
        """Print a text in the middle of the screen"""
        # --- just to be sure we are going to remove both
        # --- the colors and the codes, otherwise centering
        # --- the message will not succeed.
        temp = self.remove_color_codes(message)
        temp = self.remove_colors(message)
        spaces = int((self.cols - len(temp)) / 2) * " "
        print(f"{spaces}{message}")

    def message(self, message="", prompt="»"):
        """Print a message to the screen"""
        col = self.colors.green
        res = self.colors.reset
        if message != "":
            message = f" {message}"
        print(f"{col}{prompt}{res}{message}")

    def error(self, message="", prompt="ε"):
        """Print an error to the screen"""
        col = self.colors.red
        res = self.colors.reset
        if message != "":
            message = f" {message}"
        print(f"{col}{prompt}{res}{message}")

    def warning(self, message="", prompt=">>"):
        """"Print a warning to the screen"""
        col = self.colors.yellow
        res = self.colors.reset
        if message != "":
            message = f" {message}"
        print(f"{col}{prompt}{res}{message}")

    def info(self, message="", prompt="►"):
        """Print some information to the screen"""
        col = self.colors.blue
        res = self.colors.reset
        if message != "":
            message = f" {message}"
        print(f"{col}{prompt}{res}{message}")

    def generate_menu(self, items):
        """Generate a simple menu"""
        menu = ""
        col = self.colors.yellow
        cya = self.colors.cyan
        res = self.colors.reset
        for item in items:
            letter = item[0]
            the_rest = item[1:]
            if letter in ['q', 'Q']:
                col = self.colors.red
                menu += "\n"
            menu += f"{cya}[{col}{letter}{cya}]{res} {the_rest}\n"
        return menu

    def bigletters(self, text):
        alphabet = [
            '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
            'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
            'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
            'u', 'v', 'w', 'x', 'y', 'z', '.', '!', '?', ' '
        ]
        letters = [
            '█▀█n█▄█', '▄█n █', '▀█n█▄', '▀▀█n▄██', '█ █n▀▀█',
            '█▀n▄█', '█▄▄n█▄█', '▀▀█n  █', '███n█▄█', '█▀█n▀▀█',
            '▄▀█n█▀█', '█▄▄n█▄█', '█▀▀n█▄▄', '█▀▄n█▄▀', '█▀▀n██▄',
            '█▀▀n█▀ ', '█▀▀n█▄█', '█ █n█▀█', '█n█', '  █n█▄█',
            '█▄▀n█ █', '█  n█▄▄', '█▀▄▀█n█ ▀ █', '█▄ █n█ ▀█',
            '█▀█n█▄█', '█▀█n█▀▀', '█▀█n▀▀█', '█▀█n█▀▄', '█▀n▄█',
            '▀█▀n █ ', '█ █n█▄█', '█ █n▀▄▀', '█ █ █n▀▄▀▄▀',
            '▀▄▀n█ █', '█▄█n █ ', '▀█n█▄', ' n▄', '█n▄', '▀█n ▄',
            'n'
        ]
        def convert(text):
            small = []
            big = []
            small.extend(text.replace("_", " ").lower())
            for letter in small:
                idx = alphabet.index(letter)
                sign = letters[idx]
                big.append(sign)
            return big

        # ----- create the bigletters now
        topline = ""
        botline = ""
        letters = convert(text)
        for letter in letters:
            parts = letter.split('n')
            topline += parts[0] + ' '
            botline += parts[1] + ' '
        return f"{topline}\n{botline}\n"

    # ----------------------------------------------------
    # ----- USER INPUT
    # ----------------------------------------------------
    def userinput(self, message="", prompt=">", lower=False):
        """Get the user input with a custom message and prompt"""
        col = self.colors.green
        res = self.colors.reset
        message = f"{col}{prompt}{res} {message} : "
        answer = input(message).lower() if lower else input(message)
        return answer

    def getyesno(self, message="", prompt=">", yesdefault=True):
        """
        Get a yes or no answer, defaults to yes
            message     the question to ask (with the ?)
            prompt      the prompt to show, default >
            yesdefault  boolean, wheter default answer is yes

            returns the answer in lowercase 
        """
        col = self.colors.green
        res = self.colors.reset

        if yesdefault:
            yesno = f"({col}Y{res}/n)"
            default = "y"
        else:
            yesno = f"(y/{col}N{res})"
            default = "n"

        answer = ""
        subloop = True
        while subloop:
            answer = input(f"{col}>{res} {message} {yesno} : ").lower()
            if answer not in ['y', 'n', 'yes', 'no', '']:
                self.error("That doesn't seem quit right...")
                sleep(2)
            else:
                answer = default if answer=="" else answer
                subloop = False
        return answer

    # ----------------------------------------------------
    # ----- TOML FILE OPERATIONS
    # ----------------------------------------------------
    def readtoml(self, path):
        """
        Reads the contents of a toml file and returns the content as a list
            path    full path to toml file
            returns list
        """
        with open(path, 'r') as f:
            data = toml.load(f)
        return data
    
    def savetoml(self, path, data):
        """
        Save the data to a toml file
            path    full path to toml file
            returns nothing
        """
        with open(path, 'w') as f:
            result = toml.dump(data, f)
        return result

    # ----------------------------------------------------
    # ----- TEXT FILE OPERATIONS
    # ----------------------------------------------------
    def readtext(self, path):
        """
        Reads the content of a text file and returns it as list
            path    Full path to text file
            returns list
        """
        with open(path, 'r') as f:
            data = f.read().splitlines()
        return data

    def savetext(self, path, data):
        """
        Save data to a text file !overwrites original file!
            data    list of lines to save
            returns nothing
        """
        with open(path, 'w') as f:
            for line in data:
                f.write(f"{line}\n")

    def appendtext(self, path, data):
        """
        Save data to a text file !appends to origal file!
            data    list of lines to save
            returns nothing
        """
        with open(path, 'a+') as f:
            for line in data:
                f.write(f"{line}\n")

    # ----------------------------------------------------
    # ----- GENERAL FILE OPERATIONS
    # ----------------------------------------------------
    def check_if_it_exists(self, path):
        return os.path.exists(path)

    def mkdir(self, path):
        return os.mkdir(path)

    def remove_file(self, path):
        return os.remove(path)

    def get_folders_in_folder(self, path, ignore=[]):
        folders = []
        for item in os.scandir(path):
            if item.is_dir() and item.name not in ignore:
                folders.append(item.name)
        return folders

    def get_contents_of_folder(self, path, extension=""):
        data = []
        if extension != "":
            extension = f".{extension}"
        for item in os.scandir(path):
            if extension in item.name :
                data.append(item.name)
        return data

    def get_contens_of_folder_recursive(self, path, extension="*"):
        return glob.iglob(f"{path}/**/*.{extension}", recursive=True)

# ----------------------------------------------------
# ----- CLASS WallPaper
# ----------------------------------------------------

class WallPaper:
    def __init__(self):
        self.colors = Colors()
        self.tools = Tools()
        self.title = "behang"
        self.home = os.path.expanduser('~')
        self.config = os.path.join(self.home, '.config', 'behang', 'config.toml')
        self.data = self.read_data()
        self.categories = ['sfw', 'nsfw']
        self.check = "√"
        self.cross = "✗"
        self.check_if_wallpapers_change_automatically()
        self.wallpapers = self.get_wallpapers()

    def check_if_wallpapers_change_automatically(self):
        # --- check systemctl if wallpaper.timer is active and enabled.
        output = getoutput("systemctl --user status wallpaper.timer")
        self.data['auto'] = True if "left\n" in output else False
        self.save_data()

    def save_data(self):
        return self.tools.savetoml(self.config, self.data)

    def read_data(self):
        return self.tools.readtoml(self.config)

    def get_active_category(self):
        return self.categories[0] if self.data['sfw'] else self.categories[1]

    def check_if_folder_exists(self, subcategory):
        category = self.get_active_category()
        path = os.path.join(self.data['folder'], category, subcategory)
        return True if os.path.exists(path) else False

    def render_title(self):
        col = self.colors.yellow
        res = self.colors.reset
        lines = [
            " ______         __                      ",
            "|   __ \\.-----.|  |--.---.-.-----.-----.",
            "|   __ <|  -__||     |  _  |     |  _  |",
            "|______/|_____||__|__|___._|__|__|___  |",
            "                                 |_____|"
        ]
        for line in lines:
            print(f"{col}{line}{res}")

    def get_wallpapers(self):
        folder = self.data['folder']
        category = self.get_active_category()
        subcategory = self.data['subcategory']
        path = os.path.join(folder, category, subcategory)
        if not os.path.exists(path):
            wallpapers = []
            self.data['subcategory'] = ""
            self.save_data()
        else:
            wallpapers = self.tools.get_contents_of_folder(path, extension='jpg')
        wallpapers.sort()
        return wallpapers

    def count_wallpapers(self):
        return len(self.wallpapers)

    def get_wallpaper_index(self):
        return self.wallpapers.index(self.data['current'])

    def togglecategory(self):
        self.data['sfw'] = False if self.data['sfw'] else True
        self.change_subcategory()

    def toggle(self, item):
        self.data[item] = True if not self.data[item] else False
        self.save_data()
        
    def toggle_autochange_wallpaper(self):
        subcmd = "enable" if self.data['auto'] else "disable"
        cmd = f"systemctl --user --now {subcmd} wallpaper.timer >> /dev/null 2>&1"
        os.system(cmd)
        self.tools.warning("Giving systemctl some time to adjust...")
        sleep(4)

    def execute_root_command(self, command):
        args = ["sudo", "-S"]
        command = command.split()
        p = Popen(
            args + command,
            stdin=PIPE,
            stderr=PIPE, universal_newlines=True
        )
        r = p.communicate(self.data["rootpw"] + "\n")[1]
        del r

    def get_output(self, command):
        output = getoutput(command)
        return output

    def get_timer_time_left(self):      
        # --- check for possible times
        output = getoutput("systemctl --user status wallpaper.timer")
        output = output.split(" ")
        weeks, days, hours, minutes = "", "", "", ""
        for idx, line in enumerate(output):
            line = line
            if "left\n" in output:
                idx = output.index("left\n") - 1
                if "min" in output[idx]:
                    minutes = output[idx]
                    hours = output[idx - 1] + " "
                    if "CET" in hours:
                        hours = ""
                elif "h" in output[idx]:
                    hours = output[idx]
                else:
                    hours = ""

        timeleft = f"{weeks}{days}{hours}{minutes}"
        if "left\n" in output:
            self.data['auto'] = True
            result = f"{timeleft}"
        else:
            self.data['audo'] = False
            result = ""
        self.save_data()
        return result
    
    def open_in_gimp(self):
        path = self.construct_wallpaper_path()
        cmd = f"gimp {path}"
        os.system(cmd)
        self.set_the_new_wallpaper()

    def construct_wallpaper_path(self):
        folder = self.data['folder']
        category = self.get_active_category()
        subcat = self.data['subcategory']
        wallpaper = self.data['current']
        path = os.path.join(folder, category, subcat, wallpaper)
        return path

    def set_sddm_grub_wallpapers(self):
        jpg = [".jpg", ".jpeg"]
        curwall = self.construct_wallpaper_path()
        cmd = "convert" if Path(curwall).suffix.lower() in jpg else "cp"

        if self.data["sddm"]:
            sddm_command = f"{cmd} {curwall} {self.data['sddmbg']}"
            self.execute_root_command(sddm_command)

        if self.data['grub']:
            grub_command = f"{cmd} {curwall} {self.data['grubbg']}"
            self.execute_root_command(grub_command)

    def set_the_new_wallpaper(self, fehbg=True):
        self.tools.hide_cursor()
        path = self.construct_wallpaper_path()
        if fehbg:
            os.system(f"feh --bg-scale {path}")
        else:
            os.system(f"feh --no-fehbg --bg-scale {path}")
        self.set_sddm_grub_wallpapers()
        self.tools.show_cursor()

    def next_wallpaper(self):
        if self.count_wallpapers() > 0:
            if self.data['current'] == "":
                newidx = 0
            else:
                newidx = self.wallpapers.index(self.data['current']) + 1
            if newidx > self.count_wallpapers() - 1:
                newidx = 0
            self.idx = newidx
            self.data['current'] = self.wallpapers[newidx]
            self.save_data()
            self.set_the_new_wallpaper()

    def previous_wallpaper(self):
        if self.count_wallpapers() > 0:
            if self.data['current'] == "":
                newidx = 0
            else:
                newidx = self.wallpapers.index(self.data['current']) - 1
            if newidx < 0:
                newidx = self.count_wallpapers() - 1
            self.idx = newidx
            self.data['current'] = self.wallpapers[newidx]
            self.save_data()
            self.set_the_new_wallpaper()

    def random_wallpaper(self):
        if self.count_wallpapers() > 0:
            chosen = self.data['current']
            while chosen == self.data['current']:
                chosen = random.choice(self.wallpapers)
            self.data['current'] = chosen
            self.save_data()
            self.set_the_new_wallpaper()

    def change_subcategory(self):
        subloop = True
        while subloop:
            self.tools.clear()
            self.render_title()
            self.tools.message("Sub-categories:")
            print()
            category = self.get_active_category()
            path = os.path.join(self.data['folder'], category)
            items = self.tools.get_folders_in_folder(path, ignore=self.data['ignore'])
            items.sort()
            valid = ['q', 'quit']
            for c, item in enumerate(items):
                print(f"[{c + 1:2}] {item}")
                valid.append(str(c + 1))
            print()
            answer = self.tools.userinput("Please choose a new sub-category")
            if answer not in valid:
                self.tools.error("That doesn't seem right...")
                sleep(2)
            elif answer in ['q', 'quit']:
                subloop = False
            else:
                self.data['subcategory'] = items[int(answer) - 1]
                self.wallpapers = self.get_wallpapers()
                if self.data['random']:
                    self.random_wallpaper()
                else:
                    self.data['current'] = self.wallpapers[0]
                self.set_the_new_wallpaper()
                self.save_data()
                subloop = False
    
    def show_command_bar(self):
        cya = self.colors.cyan
        yel = self.colors.yellow
        res = self.colors.reset
        items = ["Next", "Previous", "Open", "Quit"]
        bar = ""
        for item in items:
            first = item[0]
            rest = item[1:]
            bar += f"{cya}[{yel}{first}{cya}]{res}{rest}  "
        print(bar)

    def check_setting(self, item):
        result = self.data[item]
        check = self.check if result else self.cross
        color = self.colors.green if result else self.colors.red
        return check, color

    def show_info(self):
        reset = self.colors.reset
        red = self.colors.red
        cyan = self.colors.cyan
        green = self.colors.green
        reset = self.colors.reset
        count = 0
        current = self.data['current']
        if self.data['subcategory'] != "":
            count = self.count_wallpapers()
        auto_check, auto_color = self.check_setting('auto')
        random_check, random_color = self.check_setting('random')
        grub_check, grub_color = self.check_setting('grub')
        sddm_check, sddm_color = self.check_setting('sddm')
        category = 'SFW' if self.data['sfw'] else 'NSFW'
        subcategory = self.data['subcategory']
        if subcategory == "":
            subcategory = f"{red}!!! CHOOSE ONE !!!{reset}"
        timeleft = self.get_timer_time_left()

        self.tools.clear()
        self.render_title()
        self.tools.message(f"Current main category : {green}{category}{reset}")
        self.tools.message(f"Current subcategory   : {green}{subcategory}{reset}")
        self.tools.message(f"Number of wallpapers  : {green}{count}{reset}")
        self.tools.message(f"Current wallpaper     : {green}{current}{reset}")
        if self.data['auto']:
            self.tools.message(f"Next wallpaper in     : {green}{timeleft}{reset}")
        
        print()
        self.tools.info(f"Auto change wallpaper {cyan}[{auto_color}{auto_check}{cyan}]{reset}")
        self.tools.info(f"Randomize wallpaper   {cyan}[{random_color}{random_check}{cyan}]{reset}")
        self.tools.info(f"Change GRUB wallpaper {cyan}[{grub_color}{grub_check}{cyan}]{reset}")
        self.tools.info(f"Change SDDM wallpaper {cyan}[{sddm_color}{sddm_check}{cyan}]{reset}")

    def show_mainmenu(self):   
        reset = self.colors.reset
        yellow = self.colors.yellow
        red = self.colors.red
        cyan = self.colors.cyan
        green = self.colors.green
        reset = self.colors.reset

        loop = True
        while loop:
            count = 0
            if self.data['subcategory'] != "":
                count = self.count_wallpapers()
            auto_check, auto_color = self.check_setting('auto')
            random_check, random_color = self.check_setting('random')
            grub_check, grub_color = self.check_setting('grub')
            sddm_check, sddm_color = self.check_setting('sddm')
            category = 'SFW' if self.data['sfw'] else 'NSFW'
            subcategory = self.data['subcategory']
            current = self.data['current']
            if subcategory == "":
                subcategory = f"{red}!!! CHOOSE ONE !!!{reset}"

            timeleft = self.get_timer_time_left()

            self.tools.clear()
            self.render_title()

            self.tools.message(f"Current main category : {green}{category}{reset}")
            self.tools.message(f"Current subcategory   : {green}{subcategory}{reset}")
            self.tools.message(f"Number of wallpapers  : {green}{count}{reset}")
            self.tools.message(f"Current wallpaper     : {green}{current}{reset}")
            if self.data['auto']:
                self.tools.message(f"Next wallpaper in     : {green}{timeleft}{reset}")
            
            print()
            print(f" {cyan}[{yellow}1{cyan}]{reset} Toggle Main category")
            print(f" {cyan}[{yellow}2{cyan}]{reset} Change subcategory")
            print()
            print(f" {cyan}[{yellow}3{cyan}]{reset} Auto change wallpaper {cyan}[{auto_color}{auto_check}{cyan}]{reset}")
            print(f" {cyan}[{yellow}4{cyan}]{reset} Randomize wallpaper   {cyan}[{random_color}{random_check}{cyan}]{reset}")
            print(f" {cyan}[{yellow}5{cyan}]{reset} Change GRUB wallpaper {cyan}[{grub_color}{grub_check}{cyan}]{reset}")
            print(f" {cyan}[{yellow}6{cyan}]{reset} Change SDDM wallpaper {cyan}[{sddm_color}{sddm_check}{cyan}]{reset}")
            print()
            print(f" {cyan}[{yellow}7{cyan}]{reset} Previous wallpaper")
            print(f" {cyan}[{yellow}8{cyan}]{reset} Next wallpaper")
            print(f" {cyan}[{yellow}9{cyan}]{reset} Random wallpaper")
            # print()
            # print(f" [{red}0{reset}] Quit")
            print()
            self.show_command_bar()
            print()
            answer = self.tools.userinput('What would you like to do?')
            if answer in ['0', 'q']:
                loop = False
            elif answer == '1':
                self.togglecategory()
                count = 0
            elif answer == '2':
                self.change_subcategory()
                self.wallpapers = self.get_wallpapers()
                count = self.count_wallpapers()
            elif answer == "3":
                self.toggle('auto')
                self.toggle_autochange_wallpaper()
            elif answer == "4":
                self.toggle('random')
                if self.data['random']:
                    self.random_wallpaper()
            elif answer == '5':
                self.toggle('grub')
            elif answer == '6':
                self.toggle('sddm')
            elif answer == '7':
                 self.random_wallpaper()
            elif answer in ['8', 'p', 'prev', 'previous']:
                if self.data['random']:
                    self.random_wallpaper()
                else:
                    self.previous_wallpaper()
            elif answer in ['9', 'n', 'next']:
                if self.data['random']:
                    self.random_wallpaper()
                else:
                    self.next_wallpaper()
            elif answer in ['o', 'open']:
                self.open_in_gimp()
            else:
                self.tools.error("That doesn't seem to be right...")
                sleep(2)  

    def run(self, command=""):
        if command == "":
            self.show_mainmenu()
        elif command in ["n", "next"]:
            if self.data['random']:
                self.random_wallpaper()
            else:
                self.next_wallpaper()
        elif command in ['p', 'prev', 'previous']:
            if self.data['random']:
                self.random_wallpaper()
            else:
                self.previous_wallpaper()
        elif command == 'info':
            self.show_info()
        elif command == 'auto':
            self.toggle('auto')
            self.toggle_autochange_wallpaper()
            self.show_info()
        elif command == 'random':
            self.toggle('random')
            if self.data['random']:
                self.random_wallpaper()
            self.show_info()
        elif command == 'grub':
            self.toggle('grub')
            self.show_info()
        elif command == 'sddm':
            self.toggle('sddm')
            self.show_info()
        elif command == 'both':
            self.toggle('grub')
            self.toggle('sddm')
            self.show_info()
        elif command == 'open':
            self.open_in_gimp()
        elif command == 'all':
            self.toggle('grub')
            self.toggle('sddm')
            self.toggle('random')
            self.toggle('auto')
            self.toggle_autochange_wallpaper()
            if self.data['random']:
                self.random_wallpaper()
            self.show_info()
        else:
            self.tools.clear()
            self.render_title()
            self.tools.error("I didn't quite catch that...")
            exit()


if __name__ == "__main__":
    wp = WallPaper()
    if len(sys.argv) == 1:
        wp.run()
    else:
        arg = sys.argv[1].lower()
        arg = "" if arg == "config" else arg
        wp.run(command=arg)
