#!/usr/bin/env python

import os
import toml
import pygame


from introduction import Introduction
from game import Game


class Launcher:
    def __init__(self):
        pygame.init()
        pygame.mixer.pre_init(44100, 16, 2, 4096)
        pygame.mixer.init()
        self.cwd = os.getcwd()
        self.configdir = os.path.join(self.cwd, 'data', 'config')
        self.screen_width = 1920
        self.screen_height = 1080
        self.screen = pygame.display.set_mode((self.screen_width,self.screen_height), pygame.FULLSCREEN)
        self.intro = Introduction(self.screen)
        self.game = Game(self.screen)
        self.clock = pygame.time.Clock()


    def read_toml(self):
        path = os.path.join(self.configdir, 'config.toml')
        data = toml.load(path)
        return data

    def run(self):
        self.clock.tick(60)
        data = self.read_toml()
        if data['play_intro']:
            self.intro.start()
        self.game.start()


if __name__ == "__main__":
    app = Launcher()
    app.run()
