random = false
sddm = false
grub = false
auto = false
setter = "feh"
walldir = "/data/pictures/walls"
style = "sfw"
category = "starwars"
prefix = "sw"
suffix = "jpg"
curwall = "sw-00028.jpg"
sddmbg = "/usr/share/sddm/themes/<YOUR_SDDM_THEME>"
grubbg = "/boot/grub/themes/<YOUR_GRUB_THEME_>"
password = "<YOUR PASSWORD HERE>"
