#!/usr/bin/env python3

from faker import Faker


class TUI:
    def __init__(self):
        pass

    def print_message(self, message):
        print(f">> {message}")

    def print_error(self, message):
        print(f"ERROR>> {message}")

    def print_warning(self, message):
        print(f"WARNING>> {message}")

    def print_info(self, index, value):
        print(f"{index} : {value}")


class FakeIdentity:
    def __init__(self):
        self.faker = Faker()
        self.tui = TUI()
        self.firstname = ""
        self.lastname = ""
        self.ssn = ""
        self.job = ""

    def generate_fake_id(self):
        self.firstname = self.faker.first_name_female()
        self.lastname = self.faker.last_name()
        self.ssn = self.faker.profile(['ssn'])['ssn']
        self.job = self.faker.profile(['job'])['job']

    def run(self):
        self.generate_fake_id()
        self.tui.print_info("Name", f"{self.firstname} {self.lastname}")
        self.tui.print_info("SSN", self.ssn)
        self.tui.print_info("Job", self.job)


if __name__ == "__main__":
    fid = FakeIdentity()
    fid.run()
