#!/usr/bin/env python
from zipit import Zipit
from dataclasses import dataclass
from time import sleep


@dataclass
class Config:
    title: str
    version: str


class Zipr(Zipit):
    def __init__(self):
        super().__init__()
        self.initialize()

    def initialize(self):
        Config.title = 'Zipr'
        Config.version = '2.01'

    def run(self):
        self.toggle_cursor()
        fulltitle = Config.title + " v" + Config.version
        self.title(fulltitle, clear=True, style=1)
        total = 100
        for n in range(total + 1):
            progressbar = self.render_progressbar(n, total)
            self.myprint(progressbar, clearline=True)
            sleep(0.3)

        self.toggle_cursor()


if __name__ == "__main__":
    app = Zipr()
    app.run()
