#!/usr/bin/env python

from city import City
from game import Game

class KatesStory:
    def __init__(self):
        self.game = Game()
        self.city = City()

    def run(self):
        self.city.generate_city()


if __name__ == "__main__":
    app = KatesStory()
    app.run()
