#!/usr/bin/env python
from variables import MC, CONFIG
from tui import *
from game import *
from time import sleep

class IoM:
    def __init__(self):
        MC.age = 18
        MC.location = "home"
        MC.bank = 50
        MC.job = "none"
        CONFIG.title = "Innocense Or Money"
        CONFIG.version = "0.0.1"
        self.tui = TUI()
        self.game = GAME()


    def run(self):
        # Game starts here
        running = True
        while running:
            options = [
                "Work",
                "Leave",
                "Computer",
                "Quit"
            ]
            self.tui.show_title(title=f"{CONFIG.title} {CONFIG.version}")
            self.tui.top_bar(options)

            action = input("> ").lower()
            if action in ['q', 'quit']:
                running = False
            else:
                match action:
                    case "w":
                        print("We're earning money")
                        sleep(1)
                    case "l":
                        print("We're moving to somehwere else")
                        sleep(1)
                    case "c":
                        self.game.use_computer()
                    case _:
                        print("I did not understand...")
                        sleep(1)

        # Game ends here
        self.tui.end_game()
        


if __name__ == "__main__":
    app = IoM()
    app.run()
